print("----------------------------")
print("MADLIBS GENERATOR")
print("----------------------------")
print("Let's go camping!")
print()
timeun = input("Give me a unit of time!")
noun1 = input("Give me a noun!")
place1 = input("Give me the name of a place!")
adj1 = input("Give me an adjective!")
noun2 = input("Give me another noun!")
adj2 = input("Give me another adjective!")
nounpl1 = input("Give me a plural noun!")
animal = input("Give me the plural name of an animal or creature!")
noun3 = input("Give me a plural noun!")
foodpl = input("Give me the plural of a food!")
adj3 = input("Give me an adjective!")
adj4 = input("Give me another adjective!")
print("----------------------------")
print("RESULT!")
print(f"Once a {timeun} we go camping. Our favorite spot is Mount {noun1.capitalize()}, located in {place1}. We spend all day hiking up the {adj1} path before setting up camp near Lake {noun2.capitalize()}. First, we pitch our tents on {adj2} ground. Then, we put our food in {nounpl1} to protect it from {animal}. Next, we gather {noun3} to start a fire with. Come nightfall, we roast {foodpl} and tell {adj3} stories. There is nothing like the {adj4} outdoors.")
print("----------------------------")
